#!/bin/bash
#*------------------------------------------------------------------------------*
#* Name: compose
#* Description: Script to control docker-compose
#*------------------------------------------------------------------------------*
#* Constants

#*------------------------------------------------------------------------------*
#* Variables
export ARCHTAG=x86_64

arch=$(uname -m | cut -b 1-3)

if [ "${arch}" = "arm" ]
then
  export ARCHTAG=arm32v7
fi
echo "$0: ARCHTAG=${ARCHTAG}"

if [ -z "${HWPORT}" ]
then
  export HWPORT=8080
fi

echo "$0: HWPORT=${HWPORT}"

#*------------------------------------------------------------------------------*
#* M A I N  P R O G R A M
#*------------------------------------------------------------------------------*

case $1 in
'up')
  docker-compose up -d && docker-compose logs -f
  ;;
'down')
  docker-compose down -v
  ;;
esac


#*------------------------------------------------------------------------------*
