version: '2'

services:
  puzzle-service:
    image: klmcwhirter/puzzle-service:${ARCHTAG}
    ports:
      - "5000:5000"
    networks:
      backend:
        aliases:
          - webapi

  huntwords:
    image: klmcwhirter/huntwords:${ARCHTAG}
    ports:
      - "${HWPORT}:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
